### ISSUE TITLE
[ BUG ] Zones compiled with Zonebuilder using the debug dll are nearly twice the size of release dll

### ISSUE THREAD

**Issue by maiyuzhe** [iw4x/iw4x-client#42]
This is an issue with the versions of iw4x I have compiled. r4355, r4354, I know for certain have this problem.  An example FF I compiled ended up as 56 MB being compiled with the iw4x release, while the size of it was 106 MB being compiled with debug iw4x.

**Comment by Rackover** [comment]
Not a bug - Check Compression.cpp
 https://github.com/iw4x/iw4x-client/blob/develop/src/Utils/Compression.cpp#L19

ZLIB is instructed to generate uncompressed zone when Zonebuilder runs in debug mode, so that problems in the zone structure can be easily identified. On release mode, Zonebuilder creates normal, compressed zones
